using TubeForge.Core.Media;
using TubeForge.Tests.Framework;

namespace TubeForge.Tests.Core;

public static class CaptionEmbedSelectionSetTests
{
    [Test]
    public static void CreatesCanonicalOrderedSelectionSet()
    {
        Assert.True(CaptionEmbedSelectionSet.TryCreate(
            [
                new CaptionEmbedSelection("en-US", IsAutoGenerated: false),
                new CaptionEmbedSelection("de", IsAutoGenerated: true)
            ],
            out var set));

        Assert.Equal("m.en-US,a.de", set.Identity);
        Assert.Equal(2, set.Selections.Count);
        Assert.Equal("en-US", set.Selections[0].LanguageCode);
        Assert.False(set.Selections[0].IsAutoGenerated);
        Assert.Equal("de", set.Selections[1].LanguageCode);
        Assert.True(set.Selections[1].IsAutoGenerated);
        Assert.True(CaptionEmbedSelectionSet.TryParseIdentity(set.Identity, out var parsed));
        Assert.Equal(set, parsed);
    }

    [Test]
    public static void RejectsEmptyDuplicateOversizedAndNonCanonicalSets()
    {
        var english = new CaptionEmbedSelection("en", IsAutoGenerated: false);
        Assert.False(CaptionEmbedSelectionSet.TryCreate([], out _));
        Assert.False(CaptionEmbedSelectionSet.TryCreate([english, english], out _));
        Assert.False(CaptionEmbedSelectionSet.TryCreate(
            Enumerable.Range(0, CaptionEmbedSelectionSet.MaximumTracks + 1)
                .Select(index => new CaptionEmbedSelection($"x-{index}", IsAutoGenerated: false)),
            out _));
        Assert.False(CaptionEmbedSelectionSet.TryParseIdentity("m.en,m.en", out _));
        Assert.False(CaptionEmbedSelectionSet.TryParseIdentity("m.en,", out _));
        Assert.False(CaptionEmbedSelectionSet.TryParseIdentity("m.en,a.de ", out _));
    }
}
