using System.Text.Json;
using System.Text.Json.Serialization;
using TubeForge.Core.Errors;
using TubeForge.Core.Media;
using TubeForge.Core.Results;

namespace TubeForge.YouTube.Sidecars;

public static class MetadataSidecarWriter
{
    private static readonly JsonSerializerOptions JsonOptions = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
    };

    public static async Task<Result<MetadataSidecarReceipt>> WriteAsync(
        VideoMetadata metadata,
        string destinationPath,
        CancellationToken cancellationToken = default)
    {
        ArgumentNullException.ThrowIfNull(metadata);
        if (string.IsNullOrWhiteSpace(destinationPath))
        {
            return Failure("Sidecar.InvalidDestination", "Select a metadata destination.");
        }

        string? partialPath = null;
        try
        {
            var destination = Path.GetFullPath(destinationPath);
            if (!destination.EndsWith(".info.json", StringComparison.OrdinalIgnoreCase))
            {
                return Failure("Sidecar.InvalidDestination", "Metadata sidecars must use the .info.json extension.");
            }

            partialPath = destination + ".part";
            if (File.Exists(destination))
            {
                return Failure("Sidecar.DestinationExists", "A metadata sidecar already exists at the destination.");
            }

            var directory = Path.GetDirectoryName(destination);
            if (string.IsNullOrWhiteSpace(directory))
            {
                return Failure("Sidecar.InvalidDestination", "The metadata destination is invalid.");
            }

            Directory.CreateDirectory(directory);
            var document = CreateDocument(metadata);
            var bytes = JsonSerializer.SerializeToUtf8Bytes(document, JsonOptions);
            await using (var output = new FileStream(
                             partialPath,
                             FileMode.Create,
                             FileAccess.Write,
                             FileShare.None,
                             32 * 1024,
                             FileOptions.Asynchronous | FileOptions.WriteThrough))
            {
                await output.WriteAsync(bytes, cancellationToken).ConfigureAwait(false);
                await output.FlushAsync(cancellationToken).ConfigureAwait(false);
                output.Flush(flushToDisk: true);
            }

            File.Move(partialPath, destination, overwrite: false);
            partialPath = null;
            return Result<MetadataSidecarReceipt>.Success(new MetadataSidecarReceipt(destination, bytes.LongLength));
        }
        catch (OperationCanceledException)
        {
            return Failure("Operation.Cancelled", "The metadata save was cancelled.");
        }
        catch (Exception exception) when (exception is ArgumentException or NotSupportedException or PathTooLongException)
        {
            return Failure(
                "Sidecar.InvalidDestination",
                "The metadata destination is invalid.",
                exception.GetType().Name);
        }
        catch (Exception exception) when (exception is IOException or UnauthorizedAccessException)
        {
            return Failure(
                "Sidecar.WriteFailed",
                "TubeForge could not save the metadata sidecar.",
                exception.GetType().Name);
        }
        finally
        {
            TryDelete(partialPath);
        }
    }

    private static object CreateDocument(VideoMetadata metadata) => new
    {
        schemaVersion = 1,
        extractor = "TubeForge",
        service = "YouTube",
        videoId = metadata.Id.Value,
        sourceUrl = $"https://www.youtube.com/watch?v={metadata.Id.Value}",
        metadata.Title,
        metadata.Channel,
        durationSeconds = metadata.Duration?.TotalSeconds,
        thumbnailUrl = metadata.ThumbnailUrl?.AbsoluteUri,
        availability = metadata.Availability.ToString(),
        captions = metadata.CaptionTracks.Select(track => new
        {
            track.LanguageCode,
            track.Name,
            track.IsAutoGenerated,
            track.IsTranslatable
        }),
        chapters = metadata.Chapters.Select(chapter => new
        {
            chapter.Title,
            startSeconds = chapter.StartTime.TotalSeconds
        }),
        formats = metadata.Formats.Select(format => new
        {
            formatId = format.FormatId,
            container = format.Container.ToString(),
            kind = format.Kind.ToString(),
            videoCodec = format.VideoCodec.ToString(),
            audioCodec = format.AudioCodec.ToString(),
            format.Width,
            format.Height,
            framesPerSecond = format.FramesPerSecond,
            format.Bitrate,
            contentLength = format.ContentLength,
            audioSampleRate = format.AudioSampleRate,
            format.IsHdr,
            format.QualityLabel
        })
    };

    private static Result<MetadataSidecarReceipt> Failure(
        string code,
        string message,
        string? detail = null) =>
        Result<MetadataSidecarReceipt>.Failure(new TubeForgeError(code, message, detail));

    private static void TryDelete(string? path)
    {
        if (string.IsNullOrWhiteSpace(path))
        {
            return;
        }

        try
        {
            File.Delete(path);
        }
        catch (IOException)
        {
        }
        catch (UnauthorizedAccessException)
        {
        }
    }
}

public sealed record MetadataSidecarReceipt(string DestinationPath, long BytesWritten);
