using System.ComponentModel;
using TubeForge.Core.Media;
using TubeForge.Downloads.Archives;
using TubeForge.YouTube.Captions;

namespace TubeForge.App.ViewModels;

public enum DownloadPresetKind
{
    BestOriginal,
    WindowsCompatibleMp4,
    SmallFile,
    Mp3_320,
    Custom
}

public sealed record DownloadPresetOption(
    DownloadPresetKind Value,
    string Label,
    string Description)
{
    public override string ToString() => Label;
}

public sealed record ArchiveOutputPresetOption(ArchiveOutputPreset Value, string Label)
{
    public override string ToString() => Label;
}

public sealed record ArchiveCaptionPreferenceOption(ArchiveCaptionPreference Value, string Label)
{
    public override string ToString() => Label;
}

public sealed record DownloadModeOption(
    DownloadMode Value,
    string Label,
    string Description)
{
    public override string ToString() => Label;
}

public sealed record OutputProcessingOption(
    OutputProfile Value,
    string Label,
    string Description)
{
    public override string ToString() => Label;
}

public sealed record FilterOption<T>(string Label, T? Value) where T : struct
{
    public override string ToString() => Label;
}

public sealed class CaptionTrackOption(CaptionTrack track) : INotifyPropertyChanged
{
    private bool _isSelectedForEmbedding;

    public CaptionTrack Track { get; } = track;

    public string Label =>
        $"{Track.Name} · {Track.LanguageCode.ToUpperInvariant()} · " +
        (Track.IsAutoGenerated ? "Auto-generated" : "Manual");

    public bool IsSelectedForEmbedding
    {
        get => _isSelectedForEmbedding;
        set
        {
            if (_isSelectedForEmbedding == value)
            {
                return;
            }

            _isSelectedForEmbedding = value;
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(nameof(IsSelectedForEmbedding)));
        }
    }

    public event PropertyChangedEventHandler? PropertyChanged;

    public override string ToString() => Label;
}

public sealed record CaptionFormatOption(
    CaptionOutputFormat Value,
    string Label,
    string Extension)
{
    public override string ToString() => Label;
}
