using TubeForge.Core.Media;
using TubeForge.YouTube.Captions;

namespace TubeForge.App.ViewModels;

public sealed record DownloadModeOption(
    DownloadMode Value,
    string Label,
    string Description)
{
    public override string ToString() => Label;
}

public sealed record FilterOption<T>(string Label, T? Value) where T : struct
{
    public override string ToString() => Label;
}

public sealed record CaptionTrackOption(CaptionTrack Track)
{
    public string Label =>
        $"{Track.Name} · {Track.LanguageCode.ToUpperInvariant()} · " +
        (Track.IsAutoGenerated ? "Auto-generated" : "Manual");

    public override string ToString() => Label;
}

public sealed record CaptionFormatOption(
    CaptionOutputFormat Value,
    string Label,
    string Extension)
{
    public override string ToString() => Label;
}
