using TubeForge.Core.Media;
using TubeForge.Downloads.Archives;
using TubeForge.YouTube.Captions;

namespace TubeForge.App.ViewModels;

public enum DownloadPresetKind
{
    BestOriginal,
    WindowsCompatibleMp4,
    SmallFile,
    Mp3_320,
    Custom
}

public sealed record DownloadPresetOption(
    DownloadPresetKind Value,
    string Label,
    string Description)
{
    public override string ToString() => Label;
}

public sealed record ArchiveOutputPresetOption(ArchiveOutputPreset Value, string Label)
{
    public override string ToString() => Label;
}

public sealed record ArchiveCaptionPreferenceOption(ArchiveCaptionPreference Value, string Label)
{
    public override string ToString() => Label;
}

public sealed record DownloadModeOption(
    DownloadMode Value,
    string Label,
    string Description)
{
    public override string ToString() => Label;
}

public sealed record OutputProcessingOption(
    OutputProfile Value,
    string Label,
    string Description)
{
    public override string ToString() => Label;
}

public sealed record FilterOption<T>(string Label, T? Value) where T : struct
{
    public override string ToString() => Label;
}

public sealed record CaptionTrackOption(CaptionTrack Track)
{
    public string Label =>
        $"{Track.Name} · {Track.LanguageCode.ToUpperInvariant()} · " +
        (Track.IsAutoGenerated ? "Auto-generated" : "Manual");

    public override string ToString() => Label;
}

public sealed record CaptionFormatOption(
    CaptionOutputFormat Value,
    string Label,
    string Extension)
{
    public override string ToString() => Label;
}
