using TubeForge.Core.Media;
using TubeForge.Core.YouTube;
using TubeForge.Downloads.Queue;
using TubeForge.Tests.Framework;

namespace TubeForge.Tests.Downloads;

public static class DownloadSourceIdentityTests
{
    [Test]
    public static void RoundTripsDirectAndAdaptiveSelections()
    {
        Assert.True(YouTubeVideoId.TryCreate("dQw4w9WgXcQ", out var videoId));

        var directValue = DownloadSourceIdentity.Create(videoId, 18);
        var adaptiveValue = DownloadSourceIdentity.Create(videoId, 401, 140);
        var convertedProfiles = new[]
        {
            OutputProfile.Mp3(320),
            OutputProfile.Aac(256),
            OutputProfile.Opus(160),
            OutputProfile.Wav,
            OutputProfile.Flac,
            OutputProfile.H264AacMp4,
            OutputProfile.H265AacMp4,
            OutputProfile.Vp9OpusWebM
        };

        Assert.True(DownloadSourceIdentity.TryParse(directValue, out var direct));
        Assert.Equal(18, direct.PrimaryFormatId);
        Assert.True(direct.AudioFormatId is null);
        Assert.True(DownloadSourceIdentity.TryParse(adaptiveValue, out var adaptive));
        Assert.Equal(401, adaptive.PrimaryFormatId);
        Assert.Equal(140, adaptive.AudioFormatId);
        foreach (var profile in convertedProfiles)
        {
            var value = DownloadSourceIdentity.Create(videoId, 140, output: profile);
            Assert.True(DownloadSourceIdentity.TryParse(value, out var converted));
            Assert.Equal(profile, converted.Output);
            Assert.Equal($"dQw4w9WgXcQ:140@{profile.Identity}", value);
        }

        var caption = new CaptionEmbedSelection("en-US", IsAutoGenerated: false);
        var captionValue = DownloadSourceIdentity.Create(
            videoId,
            401,
            140,
            OutputProfile.H264AacMp4,
            caption);
        Assert.True(DownloadSourceIdentity.TryParse(captionValue, out var captioned));
        Assert.Equal(caption, captioned.Caption);
        Assert.Equal(
            $"dQw4w9WgXcQ:401+140@{OutputProfile.H264AacMp4.Identity}~m.en-US",
            captionValue);

        var chaptersValue = DownloadSourceIdentity.Create(
            videoId,
            401,
            140,
            OutputProfile.H264AacMp4,
            caption,
            embedChapters: true);
        Assert.True(DownloadSourceIdentity.TryParse(chaptersValue, out var chaptered));
        Assert.True(chaptered.EmbedChapters);
        Assert.Equal(caption, chaptered.Caption);
        Assert.Equal(
            $"dQw4w9WgXcQ:401+140@{OutputProfile.H264AacMp4.Identity}~m.en-US^chapters",
            chaptersValue);

        var splitValue = DownloadSourceIdentity.Create(
            videoId,
            401,
            140,
            OutputProfile.H264AacMp4,
            caption,
            embedChapters: true,
            splitChapters: true);
        Assert.True(DownloadSourceIdentity.TryParse(splitValue, out var split));
        Assert.True(split.EmbedChapters);
        Assert.True(split.SplitChapters);
        Assert.Equal(
            $"dQw4w9WgXcQ:401+140@{OutputProfile.H264AacMp4.Identity}~m.en-US^chapters+split",
            splitValue);

        Assert.True(MediaTrimRange.TryCreate(
            TimeSpan.FromSeconds(5),
            TimeSpan.FromMinutes(1),
            out var trimRange));
        var trimmedValue = DownloadSourceIdentity.Create(
            videoId,
            401,
            140,
            OutputProfile.H264AacMp4,
            caption,
            embedChapters: true,
            splitChapters: true,
            trim: trimRange);
        Assert.True(DownloadSourceIdentity.TryParse(trimmedValue, out var trimmed));
        Assert.Equal(trimRange, trimmed.Trim);
        Assert.Equal(
            $"dQw4w9WgXcQ:401+140@{OutputProfile.H264AacMp4.Identity}~m.en-US^chapters+split%5000-60000",
            trimmedValue);

        var sponsorBlock = new SponsorBlockSelection(
            SponsorBlockMode.Remove,
            SponsorBlockCategories.Sponsor | SponsorBlockCategories.Intro);
        var sponsorValue = DownloadSourceIdentity.Create(
            videoId,
            401,
            140,
            OutputProfile.H264AacMp4,
            trim: trimRange,
            sponsorBlock: sponsorBlock);
        Assert.True(DownloadSourceIdentity.TryParse(sponsorValue, out var sponsored));
        Assert.Equal(sponsorBlock, sponsored.SponsorBlock);
        Assert.Equal(
            $"dQw4w9WgXcQ:401+140@{OutputProfile.H264AacMp4.Identity}%5000-60000&remove.sponsor,intro",
            sponsorValue);
    }

    [Test]
    public static void RejectsMalformedAndAmbiguousIdentities()
    {
        foreach (var value in new[]
                 {
                     "", "bad:18", "dQw4w9WgXcQ", "dQw4w9WgXcQ:0", "dQw4w9WgXcQ:18+",
                     "dQw4w9WgXcQ:18+0", "dQw4w9WgXcQ:18+140+251", "dQw4w9WgXcQ:18:140",
                     "dQw4w9WgXcQ:140@", "dQw4w9WgXcQ:140@native", "dQw4w9WgXcQ:140@mp3-96",
                     "dQw4w9WgXcQ:140@mp3-320@mp3-192", "dQw4w9WgXcQ:140@aac-96",
                     "dQw4w9WgXcQ:140@opus-320", "dQw4w9WgXcQ:140@wav-0",
                     "dQw4w9WgXcQ:140@flac-0", "dQw4w9WgXcQ:140@unknown-192",
                     "dQw4w9WgXcQ:401+140@h264-aac-mp4-100", "dQw4w9WgXcQ:18~",
                     "dQw4w9WgXcQ:18~x.en", "dQw4w9WgXcQ:18~m.-en",
                     "dQw4w9WgXcQ:18~m.en--US", "dQw4w9WgXcQ:18~m.en~a.de",
                     "dQw4w9WgXcQ:18^", "dQw4w9WgXcQ:18^chapter",
                     "dQw4w9WgXcQ:18^chapters^chapters", "dQw4w9WgXcQ:18^chapters~m.en",
                     "dQw4w9WgXcQ:18^split+chapters", "dQw4w9WgXcQ:18^chapters+split+split",
                     "dQw4w9WgXcQ:18%0-0", "dQw4w9WgXcQ:18%1000-2000%3000-4000",
                     "dQw4w9WgXcQ:18&", "dQw4w9WgXcQ:18&remove.sponsor,sponsor",
                     "dQw4w9WgXcQ:18&remove.unknown", "dQw4w9WgXcQ:18&chapters.intro&remove.sponsor"
                 })
        {
            Assert.False(DownloadSourceIdentity.TryParse(value, out _));
        }
    }
}
