namespace TubeForge.Core.Media;

public sealed record CaptionTrack
{
    public required Uri Url { get; init; }

    public required string LanguageCode { get; init; }

    public required string Name { get; init; }

    public string VssId { get; init; } = string.Empty;

    public bool IsAutoGenerated { get; init; }

    public bool IsTranslatable { get; init; }
}
