namespace TubeForge.Core.Media;

public readonly record struct CaptionEmbedSelection(string LanguageCode, bool IsAutoGenerated)
{
    private const int MaximumLanguageCodeLength = 35;

    public bool IsValid =>
        !string.IsNullOrWhiteSpace(LanguageCode) &&
        LanguageCode.Length <= MaximumLanguageCodeLength &&
        char.IsAsciiLetter(LanguageCode[0]) &&
        char.IsAsciiLetterOrDigit(LanguageCode[^1]) &&
        !LanguageCode.Contains("--", StringComparison.Ordinal) &&
        LanguageCode.All(character => char.IsAsciiLetterOrDigit(character) || character == '-');

    public string Identity => $"{(IsAutoGenerated ? 'a' : 'm')}.{LanguageCode}";

    public static bool TryParseIdentity(string? value, out CaptionEmbedSelection selection)
    {
        selection = default;
        if (value is null || value.Length < 3 || value[1] != '.' || value[0] is not ('a' or 'm'))
        {
            return false;
        }

        selection = new CaptionEmbedSelection(value[2..], value[0] == 'a');
        return selection.IsValid;
    }
}
